# Generated by Django 6.0.6 on 2026-07-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='folder',
            field=models.CharField(default='images', max_length=200),
        ),
    ]
